Repository opendatadiscovery/odd-collector-gcp, pull requests merged in 2023-07, with the labels that each got.

#19 Bigtable adapter
  odd_collector_gcp/adapters/bigtable/README.md
  odd_collector_gcp/adapters/bigtable/screenshots/bigtable_odd_ui.png
Labels: kind: chore

#18 Adapter for Google Cloud Storage
  README.md
  config_examples/gcs.yaml
  odd_collector_gcp/__main__.py
  odd_collector_gcp/adapters/gcs/README.md
  odd_collector_gcp/adapters/gcs/__init__.py
  odd_collector_gcp/adapters/gcs/adapter.py
  odd_collector_gcp/adapters/gcs/domain/__init__.py
  odd_collector_gcp/adapters/gcs/domain/dataset.py
  odd_collector_gcp/adapters/gcs/domain/models.py
  odd_collector_gcp/adapters/gcs/domain/parameters.py
  odd_collector_gcp/adapters/gcs/file_system.py
  odd_collector_gcp/adapters/gcs/logger.py
  odd_collector_gcp/adapters/gcs/mapper/__init__.py
  odd_collector_gcp/adapters/gcs/mapper/bucket.py
  odd_collector_gcp/adapters/gcs/mapper/column.py
  odd_collector_gcp/adapters/gcs/mapper/dataset.py
  odd_collector_gcp/adapters/gcs/mapper/gcs_field_type_transformer.py
  odd_collector_gcp/adapters/gcs/mapper/grammar/gcs_field_type_grammar.lark
  odd_collector_gcp/adapters/gcs/utils.py
  odd_collector_gcp/domain/dataset_config.py
  odd_collector_gcp/domain/plugin.py
  odd_collector_gcp/domain/to_data_entity.py
  odd_collector_gcp/errors.py
  odd_collector_gcp/filesystem/pyarrow_fs.py
  odd_collector_gcp/utils/parse_gcs_url.py
  pyproject.toml
Labels: kind: chore, kind: feature

#21 Adapter for delta tables in GCS
  README.md
  config_examples/gcs_delta.yaml
  odd_collector_gcp/__init__.py
  odd_collector_gcp/__main__.py
  odd_collector_gcp/__version__.py
  odd_collector_gcp/adapters/gcs/mapper/dataset.py
  odd_collector_gcp/adapters/gcs_delta/__init__.py
  odd_collector_gcp/adapters/gcs_delta/adapter.py
  odd_collector_gcp/adapters/gcs_delta/client.py
  odd_collector_gcp/adapters/gcs_delta/logger.py
  odd_collector_gcp/adapters/gcs_delta/mappers/__init__.py
  odd_collector_gcp/adapters/gcs_delta/mappers/delta_table.py
  odd_collector_gcp/adapters/gcs_delta/mappers/field.py
  odd_collector_gcp/adapters/gcs_delta/mappers/grammar/field_types.lark
  odd_collector_gcp/adapters/gcs_delta/mappers/metadata.py
  odd_collector_gcp/adapters/gcs_delta/models/__init__.py
  odd_collector_gcp/adapters/gcs_delta/models/field.py
  odd_collector_gcp/adapters/gcs_delta/models/table.py
  odd_collector_gcp/domain/plugin.py
  odd_collector_gcp/logger.py
  odd_collector_gcp/utils/dates.py
  odd_collector_gcp/utils/remove_gcs_protocol.py
  poetry.lock
  pyproject.toml
Labels: kind: chore, kind: feature

#22 Fix for delta tables filter
  README.md
  config_examples/gcs_delta.yaml
  odd_collector_gcp/domain/plugin.py
Labels: kind: chore, kind: bug
